### ISSUE TITLE
Typo in file "eeprom5.txt"

### ISSUE THREAD

**Issue by MDecker-MobileComputing** [NikolaiRadke/Schimpfolino#4]
Word "Folikel" in file `eeprom5.txt` should be replace with "follikel": 

* Like the other words in this file, the word should start with a lower case letter.
* Right spelling with two "L" after the "O": [Follikel](https://www.duden.de/rechtschreibung/Follikel)

**Comment by NikolaiRadke** [comment]
Thanks!!
